#!/usr/bin/env node
/**
 * scripts/build.mjs — TaskFlow content-hashed build pipeline.
 *
 * Stage A (current): generates hashed assets + manifest + validates consistency.
 * app.html and sw.js keep using ?v= pins for now.
 *
 * Usage:
 *   node scripts/build.mjs          # build hashed assets + manifest
 *   node scripts/build.mjs --check  # verify committed output is current
 *   node scripts/build.mjs --apply  # also update app.html and sw.js
 */

import { readFileSync, writeFileSync, readdirSync, statSync, unlinkSync, existsSync } from 'fs';
import { join, extname } from 'path';
import { execSync } from 'child_process';
import { createHash } from 'crypto';
import { createRequire } from 'module';

const require_ = createRequire(import.meta.url);
const ROOT = join(import.meta.dirname, '..');
const HASH_LEN = 8;

let esbuild;
try {
  esbuild = require_('esbuild');
} catch {
  execSync('npm install esbuild@0.24.2 --save-dev', { cwd: ROOT, stdio: 'inherit' });
  esbuild = require_('esbuild');
}

// ── Helpers ──────────────────────────────────────────────────────────
function fileHash(data) {
  const buf = Buffer.isBuffer(data) ? data : readFileSync(data);
  return createHash('sha256').update(buf).digest('hex').slice(0, HASH_LEN);
}

function jsSources() {
  return readdirSync(join(ROOT, 'js'))
    .filter(f =>
      f.endsWith('.js') &&
      !f.endsWith('.min.js') &&
      !f.match(/\.[0-9a-f]{8}\.js$/)
    )
    .sort()
    .map(f => 'js/' + f);
}

function cssSources() {
  return readdirSync(join(ROOT, 'css'))
    .filter(f =>
      f.endsWith('.css') &&
      !f.endsWith('.min.css') &&
      !f.startsWith('_v') &&
      !f.match(/\.[0-9a-f]{8}\.css$/)
    )
    .sort()
    .map(f => 'css/' + f);
}

function hashTree(files) {
  const h = createHash('sha256');
  for (const f of files) {
    h.update(readFileSync(join(ROOT, f)));
    h.update(Buffer.from('\0'));
  }
  return h.digest('hex').slice(0, HASH_LEN);
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ── Build ────────────────────────────────────────────────────────────
async function build() {
  const isCheck = process.argv.includes('--check');
  const isApply = process.argv.includes('--apply');
  if (isCheck) return check();

  console.log('Building TaskFlow assets…');
  const startTime = Date.now();

  const sources = [...jsSources(), ...cssSources()].sort();
  const manifest = {};
  const treeHash = hashTree(sources);

  for (const src of sources) {
    const fullSrc = join(ROOT, src.replace(/\//g, '\\'));
    const ext = extname(src);
    const basename = src.replace(/\.[^.]+$/, '');

    const sourceCode = readFileSync(fullSrc, 'utf8');
    let minified;

    if (ext === '.js') {
      const result = await esbuild.transform(sourceCode, {
        minify: true, target: 'es2020', charset: 'utf8', sourcefile: src,
      });
      minified = result.code;
    } else {
      const result = await esbuild.transform(sourceCode, {
        loader: 'css', minify: true, sourcefile: src,
      });
      minified = result.code;
    }

    // Hash the minified output
    const hash = fileHash(Buffer.from(minified));
    const outName = `${basename}.${hash}${ext}`;
    const outPath = join(ROOT, outName.replace(/\//g, '\\'));

    // Verify JS output parses
    if (ext === '.js') {
      const tmpOut = join(ROOT, '._build_tmp' + ext);
      writeFileSync(tmpOut, minified, 'utf8');
      try {
        execSync(`node --check "${tmpOut}"`, { cwd: ROOT, encoding: 'utf8' });
      } catch {
        console.error(`  FAIL node --check: ${src}`);
        process.exit(1);
      } finally {
        try { unlinkSync(tmpOut); } catch {}
      }
    }

    // Write final hashed file
    writeFileSync(outPath, minified, 'utf8');

    manifest[src] = { file: outName, hash };
    const srcSize = statSync(fullSrc).size;
    const outSize = statSync(outPath).size;
    const pct = srcSize ? Math.round((1 - outSize / srcSize) * 100) : 0;
    console.log(`  ${src} → ${outName}  ${srcSize}→${outSize} (${pct}% off)`);
  }

  // Write manifest
  manifest._treeHash = treeHash;
  writeFileSync(join(ROOT, 'asset-manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  console.log(`\nManifest: ${Object.keys(manifest).length - 1} hashed entries`);

  // Write runtime asset map (for lazy-loaded modules)
  const assetMap = {};
  for (const [src, info] of Object.entries(manifest)) {
    if (src.startsWith('_')) continue;
    assetMap[src] = info.file;
  }
  writeFileSync(
    join(ROOT, 'asset-map.js'),
    `/* Auto-generated by scripts/build.mjs — DO NOT EDIT */\nwindow.TaskFlowAssetMap = ${JSON.stringify(assetMap, null, 2)};\n`,
    'utf8'
  );
  console.log('Asset map: asset-map.js');

  // Stage B (--apply): update app.html and sw.js
  if (isApply) {
    updateAppHtml(manifest);
    updateSW(manifest);
  }

  console.log(`\nBuild complete in ${Date.now() - startTime}ms.`);
}

// ── Update app.html (--apply only) ───────────────────────────────────
function updateAppHtml(manifest) {
  const htmlPath = join(ROOT, 'app.html');
  let html = readFileSync(htmlPath, 'utf8');

  for (const [src, info] of Object.entries(manifest)) {
    if (src.startsWith('_')) continue;
    const ext = extname(src);
    const minName = src.replace(ext, `.min${ext}`);

    const pattern = new RegExp(
      `((?:src|href)="${escapeRegex(minName)})(?:\\?v=\\d+)?"`,
      'g'
    );
    html = html.replace(pattern, `$1"${info.file}"`);

    const patternSq = new RegExp(
      `((?:src|href)='${escapeRegex(minName)})(?:\\?v=\\d+)?'`,
      'g'
    );
    html = html.replace(patternSq, `$1${info.file}'`);
  }

  writeFileSync(htmlPath, html, 'utf8');
  console.log('Updated app.html');
}

// ── Update SW (--apply only) ─────────────────────────────────────────
function updateSW(manifest) {
  const swPath = join(ROOT, 'sw.js');
  let sw = readFileSync(swPath, 'utf8');

  const entries = [
    './', './index.html', './app.html', './privacy.html',
    './terms.html', './data-and-security.html', './manifest.json',
    './css/tokens.css', './css/landing.css', './css/legal.css',
    './icons/ui-sprite.svg', './icons/icon-192.png',
    './icons/icon-512.png', './icons/icon-maskable-512.png',
  ];

  const fontsDir = join(ROOT, 'fonts');
  if (existsSync(fontsDir)) {
    for (const f of readdirSync(fontsDir).sort()) {
      if (f.endsWith('.woff2')) entries.push(`./fonts/${f}`);
    }
  }

  for (const [src, info] of Object.entries(manifest).sort((a, b) => a[0].localeCompare(b[0]))) {
    if (src.startsWith('_')) continue;
    entries.push(`./${info.file}`);
  }

  const manifestHash = fileHash(join(ROOT, 'asset-manifest.json'));
  const shellBlock = `const APP_SHELL = [\n  ${entries.map(e => `'${e}'`).join(',\n  ')},\n];`;

  sw = sw.replace(/const APP_SHELL = \[[\s\S]*?\];/, shellBlock);
  sw = sw.replace(/const CACHE = 'taskflow-v\d+';/, `const CACHE = 'taskflow-${manifestHash}';`);
  sw = sw.replace(/\/\/ Lazy module version[^\n]*\nconst LAZY_V = 'v1';\n?/, '');

  writeFileSync(swPath, sw, 'utf8');
  console.log(`Updated sw.js (CACHE: taskflow-${manifestHash})`);
}

// ── Check mode ───────────────────────────────────────────────────────
function check() {
  const manifestPath = join(ROOT, 'asset-manifest.json');
  if (!existsSync(manifestPath)) {
    console.error('FAIL: asset-manifest.json not found. Run: npm run build');
    process.exit(1);
  }

  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  let ok = true;
  let checked = 0;

  for (const [src, info] of Object.entries(manifest)) {
    if (src.startsWith('_')) continue;
    checked++;

    const outPath = join(ROOT, info.file);
    if (!existsSync(outPath)) {
      console.error(`  FAIL: ${info.file} missing (for ${src})`);
      ok = false;
      continue;
    }
    const actualHash = fileHash(outPath);
    if (actualHash !== info.hash) {
      console.error(`  FAIL: ${info.file} hash mismatch (expected ${info.hash}, got ${actualHash})`);
      ok = false;
    }
  }

  // Verify asset-map.js exists
  if (!existsSync(join(ROOT, 'asset-map.js'))) {
    console.error('  FAIL: asset-map.js missing. Run: npm run build');
    ok = false;
  }

  // Source tree hash check
  const sources = [...jsSources(), ...cssSources()].sort();
  const currentHash = hashTree(sources);
  if (manifest._treeHash && currentHash !== manifest._treeHash) {
    console.error(`  FAIL: source tree changed (manifest: ${manifest._treeHash}, current: ${currentHash}). Run: npm run build`);
    ok = false;
  }

  if (ok) {
    console.log(`ALL ${checked} hashed assets verified. Manifest consistent.`);
    return 0;
  } else {
    console.error('\nBuild output is stale — run: npm run build');
    return 1;
  }
}

// ── Main ─────────────────────────────────────────────────────────────
try {
  const exitCode = await build();
  if (exitCode !== undefined && exitCode !== 0) process.exit(exitCode);
} catch (err) {
  console.error('Build failed:', err.message || err);
  process.exit(1);
}
